import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.scss"
import "./reset.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "George King & Six Adepts PMA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
